# Generated by Django 4.2.1 on 2023-07-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
